# Copyright 2018 Cargill Incorporated
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

version: '3.6'

services:

  settings-tp:
    build:
      context: ../..
      dockerfile: bgx/docker/settings/Dockerfile-${DISTR}
      args:
        - http_proxy
        - https_proxy
        - no_proxy
        - BGX_TOP=bgx
    image: sawtooth-settings-tp-bgx:${ISOLATION_ID}
    networks: 
    - network1
    environment:
    - SAWTOOTH_HOME=/project/${BGX_TOP}/data-bgx
    volumes:
      - ../..:/project/${BGX_TOP}
    container_name: sawtooth-settings-tp-bgx
    depends_on:
      - validator
    command: |
      bash -c "
        bgx/bin/protogen
        cd families/settings
        python3 setup.py clean --all
        python3 setup.py build
        settings-tp -vv -C tcp://validator:4004
      "
    stop_signal: SIGKILL

  bgt-tp-python:
    build:
      context: ../..
      dockerfile: bgx/families/bgt_python/Dockerfile-${DISTR}
      args:
        - http_proxy
        - https_proxy
        - no_proxy
        - BGX_TOP=bgx
    image: bgt-tp-python-bgx:${ISOLATION_ID}
    environment:
    - SAWTOOTH_HOME=/project/${BGX_TOP}/data-bgx
    networks:
    - network1
    volumes:
      - ../..:/project/${BGX_TOP}
    container_name: bgt-tp-python-bgx
    depends_on:
      - validator
    command: |
      bash -c "
        bgx/bin/protogen
        cd bgx/families/bgt_python
        python3 setup.py clean --all
        python3 setup.py build
        bgt-tp-python -vv -C tcp://validator:4004
      "
    stop_signal: SIGKILL


  smart-bgt-tp-python:
    build:
      context: ../..
      dockerfile: bgx/families/smart_bgt_python/Dockerfile
      args:
        - http_proxy
        - https_proxy
        - no_proxy
        - BGX_TOP=bgx
    image: smart-bgt-tp-python-bgx:${ISOLATION_ID}
    environment:
    - SAWTOOTH_HOME=/project/${BGX_TOP}/data-bgx
    networks:
    - network1
    volumes:
      - ../..:/project/${BGX_TOP}
    container_name: smart-bgt-tp-python-bgx
    depends_on:
      - validator
    command: |
      bash -c "
        bgx/bin/protogen
        cd bgx/families/smart_bgt_python
        python3 setup.py clean --all
        python3 setup.py build
        ../../bin/smart-bgt-tp-python -vv -C tcp://validator:4004
      "
    stop_signal: SIGKILL

  client:
    build:
      context: ../..
      dockerfile: bgx/docker/sawtooth-shell-${DISTR}
      args:
        - http_proxy
        - https_proxy
        - no_proxy
        - BGX_TOP=bgx
    image: sawtooth-shell-bgx:${ISOLATION_ID}
    networks:
    - network1
    environment:
    - SAWTOOTH_HOME=/project/${BGX_TOP}/data-bgx
    volumes:
      - ../..:/project/${BGX_TOP}
    container_name: sawtooth-shell-bgx
    depends_on:
      - validator
    command: |
      bash -c "
        ls -l;sawtooth keygen --force &&
        tail -f /dev/null
      "
    stop_signal: SIGKILL


  validator:
    build:
      context: ../..
      dockerfile: bgx/docker/validator/Dockerfile-${DISTR}
      args:
        - http_proxy
        - https_proxy
        - no_proxy
        - BGX_TOP=bgx
    image: sawtooth-validator-bgx:${ISOLATION_ID}
    networks:
    - network1
    environment:
    - SAWTOOTH_HOME=/project/${BGX_TOP}/data-bgx
    volumes:
      - ../..:/project/${BGX_TOP}
    container_name: sawtooth-validator-bgx
    expose:
      - 4004
      - 8800
      - 5050
    ports:
      - "4004:4004"
      - "8800:8800"
    # start the validator with an empty genesis batch
    # cargo build --release sawadm keygen && sawtooth keygen my_key && sawset genesis -k /root/.sawtooth/keys/my_key.priv && sawadm genesis config-genesis.batch && 
    command: |
      bash -c "
        bgx/bin/protogen
        cd validator
        python3 setup.py clean --all
        python3 setup.py build
        mkdir -p bin
        mkdir -p lib
        if [ -d 'target' ]; then echo 'Already build'; else cargo build --release; fi
        if [ -f 'bin/sawtooth-validator' ]; then echo 'Already copied'; else cp ./target/release/sawtooth-validator bin/sawtooth-validator; fi
        if [ -f 'lib/libsawtooth_validator.so' ]; then echo 'Already copied'; else cp ./target/release/libsawtooth_validator.so lib/libsawtooth_validator.so; fi
        sawadm keygen
        sawtooth keygen my_key
        sawset proposal create -k /root/.sawtooth/keys/my_key.priv -o sawset.batch sawtooth.consensus.algorithm=pbfts sawtooth.consensus.pbft.max_log_size=20 sawtooth.consensus.pbft.nodes=\"{'0281e398fc978e8d36d6b2244c71e140f3ee464cb4c0371a193bb0a5c6574810ba': 'leader','028c7e06db3af50a9958390e3e29f166b1cf6198586acf37cde46c8ea54e4a79ef': 'plink'}\"
        sawset genesis -k /root/.sawtooth/keys/my_key.priv
        #ls -l /var/lib/
        rm -f ../data-bgx/data/* ../data-bgx/logs/*.log*;sawadm genesis config-genesis.batch sawset.batch 
        sawtooth-validator -vv  \
            --endpoint tcp://validator:8800 \
            --bind component:tcp://eth0:4004 \
            --bind network:tcp://eth0:8800 \
            --bind consensus:tcp://eth0:5050 \
      "
    stop_signal: SIGKILL

  bgx-api:
    build:
      context: ../..
      dockerfile: bgx/rest-api/Dockerfile-${DISTR}
      args:
        - http_proxy   
        - https_proxy
        - no_proxy
        - BGX_TOP=bgx
    image: bgx-rest-api
    environment:
    - SAWTOOTH_HOME=/project/${BGX_TOP}/data-bgx
    volumes:
      - ../..:/project/${BGX_TOP}
    container_name: bgx-api
    networks:
    - network1
    ports:
      - "8018:8018" 
    depends_on:
       - validator
    command: |
      bash -c "
        bgx/bin/protogen
        cd bgx/rest-api
        python3 setup.py clean --all
        python3 setup.py build
        bgx-rest-api -vv --connect tcp://validator:4004 --bind bgx-api:8018
      "
    stop_signal: SIGKILL


  devmode-python:
   build:
     context: ../..
     dockerfile: bgx/consensus/devmode_python/Dockerfile-${DISTR}
     args:
       - http_proxy
       - https_proxy
       - no_proxy
       - BGX_TOP=bgx
   image: devmode-python-bgx:${ISOLATION_ID}
   networks:
   - network1
   environment:
   - SAWTOOTH_HOME=/project/${BGX_TOP}/data-bgx
   volumes:
     - ../..:/project/${BGX_TOP}
   container_name: devmode-python-bgx
   depends_on:
     - validator
   command: |
     bash -c "
       bgx/bin/protogen
       cd bgx/consensus/devmode_python
       python3 setup.py clean --all
       python3 setup.py build
       devmode-python -vv --connect tcp://validator:5050 --component tcp://validator:4004
     "
   stop_signal: SIGKILL


#  pbft-python:
#    build:
#      context: ../..
#      dockerfile: bgx/consensus/pbft_python/Dockerfile-${DISTR}
#      args:
#        - http_proxy
#        - https_proxy
#        - no_proxy
#        - BGX_TOP=bgx
#    image: sawtooth-pbft-python-bgx:${ISOLATION_ID}
#    networks:
#    - network1
#    environment:
#    - SAWTOOTH_HOME=/project/${BGX_TOP}/data-bgx
#    volumes:
#      - ../..:/project/${BGX_TOP}
#    container_name: sawtooth-pbft-python-bgx
#    depends_on:
#      - validator
##      - bgx-registry
#    command: |
#      bash -c "
#        bgx/bin/protogen
#        cd bgx/consensus/pbft_python
#        python3 setup.py clean --all
#        python3 setup.py build
#        pbft-python -vv --connect tcp://validator:5050 --component tcp://validator:4004
#      "
#    stop_signal: SIGKILL


  settings-tp-2:
    build:
      context: ../..
      dockerfile: bgx/docker/settings/Dockerfile-${DISTR}
      args:
        - http_proxy
        - https_proxy
        - no_proxy
        - BGX_TOP=bgx
    image: sawtooth-settings-tp-bgx2:${ISOLATION_ID}
    networks: 
    - network1
    environment:
    - SAWTOOTH_HOME=/project/${BGX_TOP}/data-bgx2
    volumes:
      - ../..:/project/${BGX_TOP}
    container_name: sawtooth-settings-tp-bgx2
    depends_on:
      - validator-2
    command: |
      bash -c "
        bgx/bin/protogen
        cd families/settings
        python3 setup.py clean --all
        python3 setup.py build
        settings-tp -vv -C tcp://validator-2:4006
      "
    stop_signal: SIGKILL

  bgt-tp-python-2:
    build:
      context: ../..
      dockerfile: bgx/families/bgt_python/Dockerfile-${DISTR}
      args:
        - http_proxy
        - https_proxy
        - no_proxy
        - BGX_TOP=bgx
    image: bgt-tp-python-bgx2:${ISOLATION_ID}
    environment:
    - SAWTOOTH_HOME=/project/${BGX_TOP}/data-bgx2
    networks:
    - network1
    volumes:
      - ../..:/project/${BGX_TOP}
    container_name: bgt-tp-python-bgx2
    depends_on:
      - validator-2
    command: |
      bash -c "
        bgx/bin/protogen
        cd bgx/families/bgt_python
        python3 setup.py clean --all
        python3 setup.py build
        bgt-tp-python -vv -C tcp://validator-2:4006
      "
    stop_signal: SIGKILL

  smart-bgt-tp-python-2:
    build:
      context: ../..
      dockerfile: bgx/families/smart_bgt_python/Dockerfile-${DISTR}
      args:
        - http_proxy
        - https_proxy
        - no_proxy
        - BGX_TOP=bgx
    image: smart-bgt-tp-python-bgx2:${ISOLATION_ID}
    environment:
    - SAWTOOTH_HOME=/project/${BGX_TOP}/data-bgx2
    networks:
    - network1
    volumes:
      - ../..:/project/${BGX_TOP}
    container_name: smart-bgt-tp-python-bgx2
    depends_on:
      - validator-2
    command: |
      bash -c "
        bgx/bin/protogen
        cd bgx/families/smart_bgt_python
        python3 setup.py clean --all
        python3 setup.py build
        smart-bgt-tp-python -vv -C tcp://validator-2:4006
      "
    stop_signal: SIGKILL


  client-2:
    build:
      context: ../..
      dockerfile: bgx/docker/sawtooth-shell-${DISTR}
      args:
        - http_proxy
        - https_proxy
        - no_proxy
        - BGX_TOP=bgx
    image: sawtooth-shell-bgx2:${ISOLATION_ID}
    networks:
    - network1
    environment:
    - SAWTOOTH_HOME=/project/${BGX_TOP}/data-bgx2
    volumes:
      - ../..:/project/${BGX_TOP}
    container_name: sawtooth-shell-bgx2
    depends_on:
      - validator-2
    command: |
      bash -c "
        sawtooth keygen --force &&
        tail -f /dev/null
      "
    stop_signal: SIGKILL


  validator-2:
    build:
      context: ../..
      dockerfile: bgx/docker/validator/Dockerfile-${DISTR}
      args:
        - http_proxy
        - https_proxy
        - no_proxy
        - BGX_TOP=bgx
    image: sawtooth-validator-bgx2:${ISOLATION_ID}
    networks:
    - network1
    environment:
    - SAWTOOTH_HOME=/project/${BGX_TOP}/data-bgx2
    volumes:
      - ../..:/project/${BGX_TOP}
    container_name: sawtooth-validator-bgx2
    depends_on:
      - validator
    expose:
      - 4006
      - 8801
      - 5051
    ports:
      - "4006:4006"
      - "8801:8801"
    # start the validator with an empty genesis batch
    # cargo build --release sawadm keygen && sawtooth keygen my_key && sawset genesis -k /root/.sawtooth/keys/my_key.priv && sawadm genesis config-genesis.batch && 
    command: |
      bash -c "
        bgx/bin/protogen
        cd validator
        python3 setup.py clean --all
        python3 setup.py build
        mkdir -p bin
        mkdir -p lib
        if [ -d 'target' ]; then echo 'Already build'; else cargo build --release; fi
        if [ -f 'bin/sawtooth-validator' ]; then echo 'Already copied'; else cp ./target/release/sawtooth-validator bin/sawtooth-validator; fi
        if [ -f 'lib/libsawtooth_validator.so' ]; then echo 'Already copied'; else cp ./target/release/libsawtooth_validator.so lib/libsawtooth_validator.so; fi
        sawadm keygen
        sawtooth keygen my_key
        sawset proposal create -k /root/.sawtooth/keys/my_key.priv -o sawset.batch sawtooth.consensus.algorithm=pbfts sawtooth.consensus.pbft.max_log_size=20 sawtooth.consensus.pbft.nodes=\"{'0281e398fc978e8d36d6b2244c71e140f3ee464cb4c0371a193bb0a5c6574810ba': 'leader','028c7e06db3af50a9958390e3e29f166b1cf6198586acf37cde46c8ea54e4a79ef': 'plink'}\"
        sawset genesis -k /root/.sawtooth/keys/my_key.priv
        #ls -l /var/lib/
        rm -f ../data-bgx2/data/* ../data-bgx2/logs/*.log* ;sawadm genesis config-genesis.batch sawset.batch
        sawtooth-validator -vv  \
            --endpoint tcp://validator-2:8801 \
            --bind component:tcp://eth0:4006 \
            --bind network:tcp://eth0:8801 \
            --bind consensus:tcp://eth0:5051 \
      "
    stop_signal: SIGKILL

  bgx-api-2:
    build:
      context: ../..
      dockerfile: bgx/rest-api/Dockerfile-${DISTR}
      args:
        - http_proxy   
        - https_proxy
        - no_proxy
        - BGX_TOP=bgx
    image: bgx-rest-api-2
    environment:
    - SAWTOOTH_HOME=/project/${BGX_TOP}/data-bgx2
    volumes:
      - ../..:/project/${BGX_TOP}
    container_name: bgx-api-2
    networks:
    - network1
    ports:
      - "8019:8019" 
    depends_on:
       - validator-2
    command: |
      bash -c "
        bgx/bin/protogen
        cd bgx/rest-api
        python3 setup.py clean --all
        python3 setup.py build
        bgx-rest-api -vv --connect tcp://validator-2:4006 --bind bgx-api-2:8019
      "
    stop_signal: SIGKILL


  devmode-python-2:
    build:
      context: ../..
      dockerfile: bgx/consensus/devmode_python/Dockerfile-${DISTR}
      args:
        - http_proxy
        - https_proxy
        - no_proxy
        - BGX_TOP=bgx
    image: sawtooth-devmode-python-bgx2:${ISOLATION_ID}
    networks:
    - network1
    environment:
    - SAWTOOTH_HOME=/project/${BGX_TOP}/data-bgx2
    volumes:
      - ../..:/project/${BGX_TOP}
    container_name: sawtooth-devmode-python-bgx2
    depends_on:
      - validator-2
    command: |
      bash -c "
        bgx/bin/protogen
        cd bgx/consensus/devmode_python
        python3 setup.py clean --all
        python3 setup.py build
        devmode-python -vv --connect tcp://validator-2:5051 --component tcp://validator-2:4006
      "
    stop_signal: SIGKILL


#  pbft-python-2:
#    build:
#      context: ../..
#      dockerfile: bgx/consensus/pbft_python/Dockerfile-${DISTR}
#      args:
#        - http_proxy
#        - https_proxy
#        - no_proxy
#        - BGX_TOP=bgx
#    image: sawtooth-pbft-python-bgx2:${ISOLATION_ID}
#    networks:
#    - network1
#    environment:
#    - SAWTOOTH_HOME=/project/${BGX_TOP}/data-bgx2
#    volumes:
#      - ../..:/project/${BGX_TOP}
#    container_name: sawtooth-pbft-python-bgx2
#    depends_on:
#      - validator-2
#    command: |
#      bash -c "
#        bgx/bin/protogen
#        cd bgx/consensus/pbft_python
#        python3 setup.py clean --all
#        python3 setup.py build
#        pbft-python -vv --connect tcp://validator-2:5051 --component tcp://validator-2:4006
#      "
#    stop_signal: SIGKILL


networks:
  network1:
     name: bgx-network
  
