# Copyright NTRLab 2019
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# FOR BGX VALIDATOR with DAG but without Rust (project validator-bgx)
# this is for cluster version - we have separate folder for cluster's peers
version: '3.6'

services:

  settings-tp:
    build:
      context: ../..
      dockerfile: bgx/docker/settings/Dockerfile-${DISTR}
      args:
        - http_proxy
        - https_proxy
        - no_proxy
        - BGX_TOP=bgx
    image: bgx-settings-tp-bgx:${ISOLATION_ID}
    networks: 
    - network1
    environment:
    - SAWTOOTH_HOME=/project/${BGX_TOP}/clusters/${C}/bgx${N}
    - PEER_HOME=/project/peer
    volumes:
      - ../..:/project/${BGX_TOP}
      - ../../../dgt_clust/${C}/bgx${N}:/project/peer
    container_name: bgx-settings-tp-bgx-${C}-${N}
    depends_on:
      - validator-bgx
    command: |
      bash -c "
        cd bgx/families/settings;rm -f /project/peer/logs/settings-*.log*;
        bgxadm node ${C} bgx${N}
        python3 setup.py clean --all
        python3 setup.py build
        settings-tp -vv -C tcp://validator-bgx-${C}-${N}:${COMP}
      "
    stop_signal: SIGKILL

  bgt-tp-python:
    build:
      context: ../..
      dockerfile: bgx/families/bgt_python/Dockerfile-${DISTR}
      args:
        - http_proxy
        - https_proxy
        - no_proxy
        - BGX_TOP=bgx
    image: bgt-tp-python-bgx:${ISOLATION_ID}
    environment:
    - SAWTOOTH_HOME=/project/${BGX_TOP}/clusters/${C}/bgx${N}
    - PEER_HOME=/project/peer
    networks:
    - network1
    volumes:
      - ../..:/project/${BGX_TOP}
      - ../../../dgt_clust/${C}/bgx${N}:/project/peer
    container_name: bgt-tp-python-bgx-${C}-${N}
    depends_on:
      - validator-bgx
    command: |
      bash -c "
        cd bgx/families/bgt_python;rm -f /project/peer/logs/bgt-*.log*;
        bgxadm node ${C} bgx${N}
        python3 setup.py clean --all
        python3 setup.py build
        bgt-tp-python -vv -C tcp://validator-bgx-${C}-${N}:${COMP}
      "
    stop_signal: SIGKILL


  stuff-tp:
    build:
      context: ../..
      dockerfile: bgx/families/smart_stuff/Dockerfile-${DISTR}
      args:
        - http_proxy
        - https_proxy
        - no_proxy
        - BGX_TOP=bgx
    image: stuff-tp-dgt:${ISOLATION_ID}
    environment:
    - SAWTOOTH_HOME=/project/${BGX_TOP}/clusters/${C}/bgx${N}
    - PEER_HOME=/project/peer
    networks:
    - network1
    volumes:
      - ../..:/project/${BGX_TOP}
      - ../../../dgt_clust/${C}/bgx${N}:/project/peer
    container_name: stuff-tp-dgt-${C}-${N}
    depends_on:
      - validator-bgx
    command: |
      bash -c "
        cd bgx/families/smart_stuff;rm -f /project/peer/logs/stuff-*.log*;
        bgxadm node ${C} bgx${N}
        python3 setup.py clean --all
        python3 setup.py build
        stuff-tp -vv -C tcp://validator-bgx-${C}-${N}:${COMP}
      "
    stop_signal: SIGKILL

#  bgx-registry-5:
#    build:
#      context: ../..
#      dockerfile: bgx/families/bgx_validator_registry/Dockerfile-${DISTR}
#      args:
#        - http_proxy
#        - https_proxy
#        - no_proxy
#        - BGX_TOP=bgx
#    image: bgx-validator-registry-5:${ISOLATION_ID}
#    environment:
#    - SAWTOOTH_HOME=/project/${BGX_TOP}/data-bgx5
#    networks:
#    - network1
#    volumes:
#      - ../..:/project/${BGX_TOP}
#    container_name: bgx-validator-registry-5
#    depends_on:
#      - validator-bgx-5
#    command: |
#      bash -c "
#        cd bgx/families/bgx_validator_registry
#        python3 setup.py clean --all
#        python3 setup.py build
#        bgx-validator-registry -vv -C tcp://validator-bgx-5:${COMP}
#      "
#    stop_signal: SIGKILL


#  smart-bgt-tp-python:
#    build:
#      context: ../..
#      dockerfile: bgx/families/smart_bgt_python/Dockerfile
#      args:
#        - http_proxy
#        - https_proxy
#        - no_proxy
#        - BGX_TOP=bgx
#    image: smart-bgt-tp-python-bgx:${ISOLATION_ID}
#    environment:
#    - SAWTOOTH_HOME=/project/${BGX_TOP}/data-bgx5
#    networks:
#    - network1
#    volumes:
#      - ../..:/project/${BGX_TOP}
#    container_name: smart-bgt-tp-python-bgx
#    depends_on:
#      - validator-bgx-5
#    command: |
#      bash -c "
#        bgx/bin/protogen
#        cd bgx/families/smart_bgt_python
#        python3 setup.py clean --all
#        python3 setup.py build
#        ../../bin/smart-bgt-tp-python -vv -C tcp://validator-bgx-5:4004
#      "
#    stop_signal: SIGKILL



  client:
    build:
      context: ../..
      dockerfile: bgx/docker/bgx-shell-${DISTR}
      args:
        - http_proxy
        - https_proxy
        - no_proxy
        - BGX_TOP=bgx
    image: shell-bgx:${ISOLATION_ID}
    networks:
    - network1
    environment:
    - SAWTOOTH_HOME=/project/${BGX_TOP}/clusters/${C}/bgx${N}
    - PEER_HOME=/project/peer
    volumes:
      - ../..:/project/${BGX_TOP}
      - ../../../dgt_clust/${C}/bgx${N}:/project/peer
    container_name: shell-bgx-${C}-${N}
    depends_on:
      - validator-bgx
    command: |
      bash -c "
        bgx keygen --force &&
        tail -f /dev/null
      "
    stop_signal: SIGKILL


  validator-bgx:
    build:
      context: ../..
      dockerfile: bgx/validator-bgx/Dockerfile-${DISTR}
      args:
        - http_proxy
        - https_proxy
        - no_proxy
        - BGX_TOP=bgx
    image: validator-bgx:${ISOLATION_ID}
    networks:
    - network1
    environment:
    - SAWTOOTH_HOME=/project/${BGX_TOP}/clusters/${C}/bgx${N}
    - PEER_HOME=/project/peer
    - ENDPOINTS=${ENDPOINTS}
    - SINGLE=${SINGLE}
    - NETWORK=${NETWORK}
    volumes:
      - ../..:/project/${BGX_TOP}
      - ../../../dgt_clust/${C}/bgx${N}:/project/peer
    container_name: validator-bgx-${C}-${N}
    expose:
      - ${COMP}
      - ${NET}
      - ${CONS}
    ports:
      - ${COMP}:${COMP}
      - ${NET}:${NET}
    # start the validator with an empty genesis batch sawtooth.consensus.algorithm=devmode and ADD sawtooth.consensus.version=0.1 /root/.dgt/keys/my_key.priv
    command: |
      bash -c "
        bgx/bin/protogen
        if [ -z ${PEERS} ]; then echo 'ONE HOST MODE'; else echo 'MANY HOST MODE (${PEERS})';add_peers.sh '${PEERS}'; fi
        cd bgx/validator-bgx
        python3 setup.py clean --all
        python3 setup.py build
        bgxadm node ${C} bgx${N};bgxadm keygen;ls -l /project/peer;
        if [ ${G} == 'Y' ]; then rm -f /project/peer/data/*; else echo 'RESTART MODE'; fi; rm -f /project/peer/logs/validator*.log* /project/peer/logs/interc*.log* ;
        bgx keygen my_key;
        echo 'GATEWAY=${SEEDS},PEERING=${PEERING},NETWORK=${NETWORK}'
        bgxset proposal create -k /project/peer/keys/validator.priv -o dgtset.batch $$(cat /project/peer/etc/dgt.conf)
        bgxset genesis -k /project/peer/keys/validator.priv -A $$(cat /project/${BGX_TOP}/clusters/c1/bgx1/keys/validator.pub) -A $$(cat /project/peer/keys/validator.pub)
        if [ ${G} == 'Y' ]; then bgxadm genesis config-genesis.batch  dgtset.batch;echo 'GENESIS MODE'; else echo 'RESTART MODE'; fi
        validator-dbgx -vv  \
            --endpoint tcp://validator-bgx-${C}-${N}:${NET} \
            --bind component:tcp://eth0:${COMP} \
            --bind network:tcp://eth0:${NET} \
            --bind consensus:tcp://eth0:${CONS} \
            --max_dag_branch 6 --scheduler parallel --peering ${PEERING} ${SEEDS} --maximum-peer-connectivity 70 \
            --opentsdb-url-off http://bgx-stats-influxdb:8086 --opentsdb-db metrics --opentsdb-username lrdata --opentsdb-password pwlrdata
      "
    stop_signal: SIGTERM
    #stop_grace_period: 600ms


  bgx-api:
    build:
      context: ../..
      dockerfile: bgx/rest-api/Dockerfile-${DISTR}
      args:
        - http_proxy   
        - https_proxy
        - no_proxy
        - BGX_TOP=bgx
    image: bgx-rest-api:${ISOLATION_ID}
    environment:
    - SAWTOOTH_HOME=/project/${BGX_TOP}/clusters/${C}/bgx${N}
    - PEER_HOME=/project/peer
    volumes:
      - ../..:/project/${BGX_TOP}
      - ../../../dgt_clust/${C}/bgx${N}:/project/peer
    container_name: bgx-api-${C}-${N}
    networks:
    - network1
    ports:
      - ${API}:${API} 
    depends_on:
       - validator-bgx
    command: |
      bash -c "
        cd bgx/rest-api;rm -f /project/peer/logs/bgx-rest-api*.log*;
        bgxadm node ${C} bgx${N}
        python3 setup.py clean --all
        python3 setup.py build
        bgx-rest-api -vv --connect tcp://validator-bgx-${C}-${N}:${COMP} --bind bgx-api-${C}-${N}:${API} --opentsdb-url http://bgx-stats-influxdb:8086 --opentsdb-db metrics --opentsdb-username lrdata --opentsdb-password pwlrdata
      "
    stop_signal: SIGKILL


  bgx-pbft:
    build:
      context: ../..
      dockerfile: bgx/consensus/bgx_pbft/Dockerfile-${DISTR}
      args:
        - http_proxy
        - https_proxy
        - no_proxy
        - BGX_TOP=bgx
    image: bgx-pbft:${ISOLATION_ID}
    networks:
    - network1
    environment:
    - SAWTOOTH_HOME=/project/${BGX_TOP}/clusters/${C}/bgx${N}
    - PEER_HOME=/project/peer
    volumes:
      - ../..:/project/${BGX_TOP}
      - ../../../dgt_clust/${C}/bgx${N}:/project/peer
    container_name: bgx-pbft-${C}-${N}
    depends_on:
      - validator-bgx
    #  - bgx-registry
    command: |
      bash -c "
        cd bgx/consensus/bgx_pbft;rm -f /project/peer/logs/pbft*.log*;
        bgxadm node ${C} bgx${N}
        python3 setup.py clean --all
        python3 setup.py build
        bgx-pbft -vv --connect tcp://validator-bgx-${C}-${N}:${CONS} --component tcp://validator-bgx-${C}-${N}:${COMP}
      "
    stop_signal: SIGKILL


#  devmode-python-5:
#   build:
#     context: ../..
#     dockerfile: bgx/consensus/devmode_python/Dockerfile-${DISTR}
#     args:
#       - http_proxy
#       - https_proxy
#       - no_proxy
#       - BGX_TOP=bgx
#   image: devmode-python-bgx-5:${ISOLATION_ID}
#   networks:
#   - network1
#   environment:
#   - SAWTOOTH_HOME=/project/${BGX_TOP}/data-bgx5
#   volumes:
#     - ../..:/project/${BGX_TOP}
#   container_name: devmode-python-bgx-5
#   depends_on:
#     - validator-bgx-5
#   command: |
#     bash -c "
#       cd bgx/consensus/devmode_python
#       python3 setup.py clean --all
#       python3 setup.py build
#       devmode-python -vv --connect tcp://validator-bgx-5:${CONS} --component tcp://validator-bgx-5:${COMP}
#     "
#   stop_signal: SIGKILL


networks:
  network1:
     name: bgx1-network
#name: bgx${N}-network
#        driver: default
#        config:
#          - subnet: "172.16.32.0/24"
          
  
